create table if not exists public.athar_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null,
  page_path text not null,
  device text not null,
  standalone boolean not null default false,
  params jsonb not null default '{}'::jsonb
);

alter table public.athar_events enable row level security;

drop policy if exists "athar_events_insert_public" on public.athar_events;
create policy "athar_events_insert_public"
  on public.athar_events
  for insert
  to anon
  with check (true);

drop policy if exists "athar_events_read_public" on public.athar_events;
create policy "athar_events_read_public"
  on public.athar_events
  for select
  to anon
  using (true);

create index if not exists athar_events_created_at_idx on public.athar_events (created_at desc);
create index if not exists athar_events_event_name_idx on public.athar_events (event_name);
