import type { AtharV2Item } from "./types";

export const ATHAR_V2_LIBRARY: AtharV2Item[] = [
  {
    id: "ayah-al-baqarah-201",
    type: "ayah",
    text: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    source: { title: "القرآن الكريم", reference: "البقرة: 201" },
    tags: ["dua", "hope", "mercy", "short"],
    occasions: ["friday_last_hour", "arafah", "ramadan", "generic"],
    priority: 94,
    weight: 9,
  },
  {
    id: "ayah-ali-imran-8",
    type: "ayah",
    text: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً",
    source: { title: "القرآن الكريم", reference: "آل عمران: 8" },
    tags: ["dua", "mercy", "hope", "short"],
    occasions: ["friday", "ramadan_last_night", "generic"],
    priority: 88,
    weight: 7,
  },
  {
    id: "ayah-al-kahf-10",
    type: "ayah",
    text: "رَبَّنَا آتِنَا مِن لَّدُنكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا",
    source: { title: "القرآن الكريم", reference: "الكهف: 10" },
    tags: ["dua", "mercy", "friday", "short"],
    occasions: ["friday", "friday_last_hour", "generic"],
    priority: 90,
    weight: 8,
  },
  {
    id: "ayah-ghafir-60",
    type: "ayah",
    text: "وَقَالَ رَبُّكُمُ ادْعُونِي أَسْتَجِبْ لَكُمْ",
    source: { title: "القرآن الكريم", reference: "غافر: 60" },
    tags: ["dua", "hope", "short"],
    occasions: ["friday_last_hour", "ramadan", "arafah", "generic"],
    priority: 92,
    weight: 9,
  },
  {
    id: "ayah-al-muzzammil-20",
    type: "ayah",
    text: "وَمَا تُقَدِّمُوا لِأَنفُسِكُم مِّنْ خَيْرٍ تَجِدُوهُ عِندَ اللَّهِ",
    source: { title: "القرآن الكريم", reference: "المزمل: 20" },
    tags: ["barakah", "hope", "short"],
    occasions: ["daily_morning", "daily_evening", "generic"],
    priority: 74,
    weight: 5,
  },
  {
    id: "ayah-at-talaq-3",
    type: "ayah",
    text: "وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ",
    source: { title: "القرآن الكريم", reference: "الطلاق: 3" },
    tags: ["tawakkul", "rizq", "short"],
    occasions: ["daily_morning", "generic"],
    priority: 82,
    weight: 7,
  },
  {
    id: "dua-sayyidul-istighfar-short",
    type: "dua",
    text: "اللهم أنت ربي لا إله إلا أنت، خلقتني وأنا عبدك، وأنا على عهدك ووعدك ما استطعت",
    source: { title: "صحيح البخاري", reference: "حديث سيد الاستغفار" },
    tags: ["forgiveness", "morning", "evening", "short"],
    occasions: ["daily_morning", "daily_evening", "ramadan_last_night", "generic"],
    priority: 86,
    weight: 7,
  },
  {
    id: "dua-allahumma-innaka-afuwwun",
    type: "dua",
    text: "اللهم إنك عفو تحب العفو فاعف عني",
    source: { title: "سنن الترمذي", reference: "دعاء ليلة القدر", verifier: "حسنه الألباني" },
    tags: ["forgiveness", "mercy", "ramadan", "short"],
    occasions: ["ramadan", "ramadan_last_night", "arafah", "generic"],
    priority: 96,
    weight: 10,
  },
  {
    id: "dua-rabbi-ghfir-li",
    type: "dua",
    text: "رب اغفر لي وتب علي إنك أنت التواب الرحيم",
    source: { title: "سنن أبي داود والترمذي", reference: "من دعاء النبي ﷺ", verifier: "صحيح" },
    tags: ["forgiveness", "mercy", "short"],
    occasions: ["ramadan_last_night", "daily_evening", "arafah", "generic"],
    priority: 84,
    weight: 6,
  },
  {
    id: "dua-allahumma-bik-asbahna",
    type: "dua",
    text: "اللهم بك أصبحنا وبك أمسينا وبك نحيا وبك نموت وإليك النشور",
    source: { title: "سنن أبي داود والترمذي", reference: "أذكار الصباح", verifier: "صحيح" },
    tags: ["morning", "tawakkul", "barakah", "short"],
    occasions: ["daily_morning", "generic"],
    priority: 89,
    weight: 8,
  },
  {
    id: "hadith-dua-friday-hour",
    type: "hadith",
    text: "في الجمعة ساعة لا يوافقها عبد مسلم وهو قائم يصلي يسأل الله شيئًا إلا أعطاه إياه",
    source: { title: "صحيح البخاري وصحيح مسلم", reference: "فضل ساعة الجمعة" },
    tags: ["friday", "dua", "hope", "short"],
    occasions: ["friday", "friday_last_hour"],
    priority: 98,
    weight: 10,
  },
  {
    id: "hadith-fasting-monday",
    type: "hadith",
    text: "ذلك يوم وُلدت فيه، ويوم بُعثت أو أُنزل عليَّ فيه",
    source: { title: "صحيح مسلم", reference: "فضل صيام يوم الاثنين" },
    tags: ["fasting", "short"],
    occasions: ["monday_preparation", "monday_fasting"],
    priority: 94,
    weight: 9,
  },
  {
    id: "hadith-best-dua-arafah",
    type: "hadith",
    text: "خير الدعاء دعاء يوم عرفة، وخير ما قلت أنا والنبيون من قبلي: لا إله إلا الله وحده لا شريك له",
    source: { title: "سنن الترمذي", reference: "دعاء يوم عرفة", verifier: "حسن" },
    tags: ["arafah", "dua", "tawhid", "forgiveness", "short"],
    occasions: ["arafah"],
    priority: 100,
    weight: 10,
  },
  {
    id: "hadith-actions-by-intentions",
    type: "hadith",
    text: "إنما الأعمال بالنيات، وإنما لكل امرئ ما نوى",
    source: { title: "صحيح البخاري وصحيح مسلم", reference: "حديث النية" },
    tags: ["barakah", "short"],
    occasions: ["daily_morning", "generic"],
    priority: 76,
    weight: 5,
  },
  {
    id: "tafsir-al-baqarah-201",
    type: "tafsir",
    text: "دعاء جامع يطلب صلاح الدنيا والآخرة والنجاة من النار.",
    source: { title: "تفسير ابن كثير والسعدي", reference: "معنى البقرة: 201" },
    tags: ["quran_meaning", "dua", "hope", "short"],
    occasions: ["friday_last_hour", "arafah", "generic"],
    priority: 80,
    weight: 5,
  },
  {
    id: "tafsir-at-talaq-3",
    type: "tafsir",
    text: "من صدق اعتماده على الله كفاه الله ما أهمه ويسر له أمره.",
    source: { title: "تفسير السعدي", reference: "معنى الطلاق: 3" },
    tags: ["quran_meaning", "tawakkul", "rizq", "short"],
    occasions: ["daily_morning", "generic"],
    priority: 78,
    weight: 5,
  },
  {
    id: "tafsir-ghafir-60",
    type: "tafsir",
    text: "في الآية أمر بالدعاء ووعد كريم بالإجابة لمن دعا ربه.",
    source: { title: "تفسير السعدي", reference: "معنى غافر: 60" },
    tags: ["quran_meaning", "dua", "hope", "short"],
    occasions: ["friday_last_hour", "ramadan", "generic"],
    priority: 82,
    weight: 6,
  },
  {
    id: "tafsir-al-kahf-10",
    type: "tafsir",
    text: "طلبوا من الله رحمة وهداية وتيسيرًا لأمرهم إلى الرشد.",
    source: { title: "تفسير ابن كثير والسعدي", reference: "معنى الكهف: 10" },
    tags: ["quran_meaning", "dua", "mercy", "friday", "short"],
    occasions: ["friday", "friday_last_hour", "generic"],
    priority: 79,
    weight: 5,
  },
];
